[build]
  base = "travel-website/client"
  command = "npm run build"
  publish = "dist"
  # This goes UP from client, then INTO the netlify folder
  functions = "../netlify/functions" 

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200