[build]
  base = "travel-website/client"
  command = "npm run build"
  publish = "dist"
  functions = "travel-website/netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

  # This rule handles the "Page Not Found" on refresh
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200